<?php echo $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>

        <?php echo $this->headMeta() ?>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <?php echo $this->placeholder('html5js') ?>    
        <![endif]-->
        <?php echo $this->headScript() ?>
        <!-- Le styles -->
        <?php echo $this->headLink() ?>

        <!-- Le fav and touch icons -->
        <?php echo $this->placeholder('favicon') ?>

        <script src="/js/jquery-1.7.1.min.js"></script>
        <script src="/js/bootstrap.js"></script>
    </head>

    <body>

        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container" style="width: auto;">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/">Timers</a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li class="active"><a href="/">Home</a></li>
                            <li><a href="#">Link</a></li>
                        </ul>
                        <form class="navbar-search pull-left" action="">
                            <input type="text" class="search-query span2" placeholder="Search">
                        </form>
                        <ul class="nav pull-right">
                            <li>
                                <a href="#">Link</a>
                            </li>
                            <li class="divider-vertical"></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Dropdown 
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Action</a>
                                    </li>
                                    <li>
                                        <a href="#">Another action</a>
                                    </li>
                                    <li>
                                        <a href="#">Something else here</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">Separated link</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <!-- /.nav-collapse -->
                </div>
            </div>
            <!-- /navbar-inner -->
        </div>


        <div class="topbar">
            <div class="fill">
                <div class="container">
                    <a class="brand" href="<?php echo $this->url('home') ?>">ZF2 Skeleton Application</a>

                    <ul class="nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
                    </ul>
                </div>
            </div>

        </div>

        <div class="container">
            <?php echo $this->raw('content'); ?>

            <footer>
                <p>&copy; 2006 - <?php echo date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>

        </div> <!-- /container -->

    </body>
</html>
